kind: Cluster
apiVersion: kind.sigs.k8s.io/v1alpha3
# 1 control plane node and 3 workers
nodes:
  # the control plane node config
  - role: control-plane
  # and the two workers
  - role: worker
    # The node port used for code server ingress controller.
    extraPortMappings:
    - containerPort: 30080
      hostPort: 80
    - containerPort: 30082
      hostPort: 443
  - role: worker
